In [2]:
#why loop is slow in python 
import  numpy as np

arr=np.array([1,2,3,4,5])
result=[]

#using a loop to square each element (slow)
for num in arr:
    result.append(num**2)
print(result)
## conclusion :- loop iteration is slow

[1, 4, 9, 16, 25]


In [3]:
#Vectrozied method uses karta data fast processes hota hai
#it work on SIMD(single intruction ,multiple data )
arr=np.array([1,2,3,4,5])
result=arr ** 2 #vectrozied opertation
print(result)

[ 1  4  9 16 25]


In [6]:
result+10# [10,10,10,10,10] in memory that type image not formed (no extra memeory is used)

array([11, 14, 19, 26, 35])

In [7]:
# Broadcasting of array (addtion )
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2

In [8]:
result

array([5, 7, 9])

In [10]:
#Brocasting array in 2D array and 1D array
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([9,4,8])
result=arr1 +arr2


In [11]:
result

array([[10,  6, 11],
       [14, 10, 15]])

In [12]:
#similating a dataset (5 samples, 3 features)
data=np.array([[10,22,31],
              [32,23,67],
              [88,76,65],
               [56,67,45],
              [45,87,98]])
mean=arr.mean(axis=0)
sd=arr.std(axis=0)
Normalized_data=(data-mean)/sd
print(Normalized_data)

[[ 4.94974747 13.43502884 19.79898987]
 [20.50609665 14.14213562 45.254834  ]
 [60.1040764  51.61879503 43.84062043]
 [37.4766594  45.254834   29.69848481]
 [29.69848481 59.39696962 67.17514421]]
