In [1]:
import numpy as np

In [2]:
!pip install numpy

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [12]:
np.eye(5)# It give the Identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [33]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[7,5,3]],dtype='float32')

In [34]:
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [7., 5., 3.]], dtype=float32)

In [21]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim

2

In [26]:
myarr.dtype

dtype('int32')

In [36]:
n=myarr.astype('float64')

In [37]:
n.dtype

dtype('float64')

In [38]:
myarr.dtype

dtype('float32')

In [39]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[7,5,3]])

In [40]:
myarr.shape

(4, 3)

In [41]:
reshaped=myarr.reshape((3,4))

In [43]:
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 5, 3]])

In [44]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 5, 3]])

In [48]:
myarr.reshape((2,6))#((2,4)) it will not doing 

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 7, 5, 3]])