In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat=arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

1

In [9]:
flat[3]

4

In [10]:
flat[1:5]

array([2, 3, 4, 5])

In [11]:
flat[:5] 

array([1, 2, 3, 4, 5])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [13]:
flat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [24]:
b=flat[3:7].copy()#This is not a slice because we are using copy method to get the copy

In [20]:
b

array([222222,      5,      6,      7])

In [21]:
b[0]=222222

In [22]:
b

array([222222,      5,      6,      7])

In [23]:
flat

array([     1,      2,      3, 222222,      5,      6,      7,      8,
            9,     11,     12,     13])

In [25]:
arr=np.array([1,54,23,53,2,3,34,5,6])

In [26]:
arr[[1,4,6]]

array([54,  2, 34])

In [37]:
flat

array([     1,      2,      3, 222222,      5,      6,      7,      8,
            9,     11,     12,     13])

In [38]:
arr[arr>3]

TypeError: '>' not supported between instances of 'list' and 'int'

In [8]:
#homework question create 3x3 array filled with random number and print its shape
import numpy as np
matrix=np.random.randint(0,100,size=(3,3))
print(matrix)
print("shape :",matrix.shape)

[[44 69 36]
 [91 28 25]
 [81 66 12]]
shape : (3, 3)


In [10]:
#convert an array of floats into integers
import numpy as np
float=np.array([[1.2,2.3,3.4],[4.5,5.4,6.4]])
print("Float matrix :",float)
integer=float.astype(int)
print("Integer matrix :",integer)


Float matrix : [[1.2 2.3 3.4]
 [4.5 5.4 6.4]]
Integer matrix : [[1 2 3]
 [4 5 6]]


In [12]:
#use fancy indexing to exract even number from [1 2 3 4 5 6 7 8]
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
even_mask=(arr %2 ==0)
even_numbers=arr[even_mask]
print(even_numbers)


[2 4 6 8]
