In [1]:
import numpy as np

In [12]:
arr=np.array([3,5,2,33])

In [13]:
np.mean(arr)

10.75

In [14]:
np.std(arr)

12.891373084353738

In [15]:
np.var(arr)

166.1875

In [16]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])

In [17]:
np.percentile(arr,50)

4.0

In [18]:
np.median(arr)

4.0

In [19]:
np.max(arr)

33

In [20]:
np.min(arr)

2

In [21]:
np.sum(arr)

43

In [22]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])