In [4]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.sum(arr, axis=1) #sum each element across element

array([ 6, 15, 24])

In [8]:
np.sum(arr,axis=0) #sum each element across row

array([12, 15, 18])

In [11]:
arr[1][1]# its indexing start with 0 

5

In [16]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [19]:
#3d array  arr3D.shape is (depth,rows,column)
arr3D=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]]])
print(arr3D[0,1,2])

6


In [28]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
#get all row of the first column
first_col=arr[:, 0]
print(first_col)

[1 4 7]


In [35]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
# Get the first row from "sheet" in a 3D array
first_rows =arr3D[:, 0 ,:]
print(first_rows)

[[0 0 0]]


In [37]:
arr3D[:, 0 ,:]=0