In [1]:
import numpy as np

In [2]:
arr=np.array([23,21,45])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr.astype("float64")

array([23., 21., 45.])

In [8]:
arr2=np.array([23,21,45], dtype="float32")

In [11]:
arr2

array([ 2.,  3., 21., 45.], dtype=float32)

In [9]:
arr2=np.array([2,3,21,45], dtype="float32")

In [10]:
arr2

array([ 2.,  3., 21., 45.], dtype=float32)

In [12]:
arr2.nbytes

16

In [13]:
arr.nbytes

12

In [17]:
arr_large=np.array([100000,2000000,3000000], dtype=np.int64)
arr_small=arr_large.astype(np.int32) #Downcasting to a smallee dtype
print(arr_small)
print(arr_large.dtype)

[ 100000 2000000 3000000]
int64


In [18]:
arr

array([23., 21., 45.], dtype=float32)